site_name: 'Example Documentation'
repo_url: https://github.com/devurandomsorg/backstage-catalog
edit_uri: edit/main/systems/podcast-system/docs

nav:
  - Home: index.md
  - Subpage: sub-page.md
  - 'Code Sample': code/code-sample.md
  - Extensions: extensions.md

plugins:
  - techdocs-core
